Games.WEB/Models/ErrorViewModel.cs
using System;
using Games.DAL;

namespace Games.WEB.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Games.WEB/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Games.BL;
using Games.DAL;

namespace Games.WEB.Controllers
{
    public class GamesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GamesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Games
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Games.Include(g => g.Developer).Include(g => g.Genres);
            ViewData["Genres"]= new SelectList(_context.Genres, "Id", "Name");
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Games/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Games
                .Include(g => g.Developer)
                .Include(g => g.Genres)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (game == null)
            {
                return NotFound();
            }

            return View(game);
        }

        // GET: Games/Create
        public IActionResult Create()
        {
            ViewData["DeveloperId"] = new SelectList(_context.Developers, "Id", "Name");
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,DeveloperId")] Game game)
        {
            if (ModelState.IsValid)
            {
                _context.Add(game);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DeveloperId"] = new SelectList(_context.Developers, "Id", "Id", game.DeveloperId);
            return View(game);
        }

        // GET: Games/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Games
                .Include(game => game.Genres)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (game == null)
            {
                return NotFound();
            }
            ViewData["DeveloperId"] = new SelectList(_context.Developers, "Id", "Name", game.DeveloperId);
            ViewData["Genres"] = new SelectList(_context.Genres.Where(g => !game.Genres.Contains(g)), "Id", "Name");
            return View(game);
        }

        // POST: Games/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,DeveloperId")] Game game)
        {
            if (id != game.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(game);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GameExists(game.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DeveloperId"] = new SelectList(_context.Developers, "Id", "Id", game.DeveloperId);
            return View(game);
        }

        // GET: Games/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var game = await _context.Games
                .Include(g => g.Developer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (game == null)
            {
                return NotFound();
            }

            return View(game);
        }

        // POST: Games/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var game = await _context.Games.FindAsync(id);
            _context.Games.Remove(game);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GameExists(int id)
        {
            return _context.Games.Any(e => e.Id == id);
        }

        public async Task<IActionResult> DeleteGenre(int gameId, int genreId)
        {
            var game = await _context.Games
                .Include(g => g.Developer)
                .Include(g => g.Genres)
                .FirstOrDefaultAsync(m => m.Id == gameId);

            game.Genres.Remove(await _context.Genres.FindAsync(genreId));
            await _context.SaveChangesAsync();
            if (game == null)
            {
                return NotFound();
            }

            return RedirectToAction("Edit", new { id = gameId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddGenre(int gameId, int[] Genres)
        {
            var game = await _context.Games
                .Include(g => g.Developer)
                .Include(g => g.Genres)
                .FirstOrDefaultAsync(m => m.Id == gameId);

            if (game == null)
            {
                return NotFound();
            }

            foreach (var i in Genres)
            {
                game.Genres.Add(await _context.Genres.FindAsync(i));
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Edit", new { id = gameId });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> FindGames(Genre genre)
        {
            if (genre == null)
            {
                return NotFound();
            }
            var applicationDbContext = _context.Games.Include(g => g.Developer).Include(g => g.Genres);
            applicationDbContext.Select(g => g.Genres.Contains(genre));
            return View(await applicationDbContext.ToListAsync());
        }
    }
}

Games.WEB/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Games.WEB.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Games.WEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Games.WEB/Views/Games/Create.cshtml
@model Games.BL.Game

@{
    ViewData["Title"] = "Create";
}

<h1>Создание игры</h1>

<h4>Игра</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Название игры</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeveloperId" class="control-label">Разработчик</label>
                <select asp-for="DeveloperId" class ="form-control" asp-items="ViewBag.DeveloperId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Обратно к списку игр</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Games.WEB/Views/Games/Delete.cshtml
@model Games.BL.Game

@{
    ViewData["Title"] = "Delete";
}

<h1>Удаление</h1>

<h3>Вы уверены, что хотите удалить игру?</h3>
<div>
    <h4>Игра</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Название игры
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            Разработчик
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Developer.Name)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index">Обратно к списку игр</a>
    </form>
</div>

Games.WEB/Views/Games/Details.cshtml
@model Games.BL.Game

@{
    ViewData["Title"] = "Details";
}

<h1>Детали</h1>

<div>
    <h4>Игра</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Название игры
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            Разработчик
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Developer.Name)
        </dd>
        <dt class="col-sm-2">
            Жанр
        </dt>
        <dd class="col-sm-10">
            @foreach (var item in Model.Genres)
            {
                <li> @item.Name</li>
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Изменить</a> |
    <a asp-action="Index">Обратно к списку игр</a>
</div>

Games.WEB/Views/Games/Edit.cshtml
@model Games.BL.Game

@{
    ViewData["Title"] = "Edit";
}

<h1>Редактирование</h1>

<h4>Игра</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label">Название игры</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeveloperId" class="control-label">Разработчик</label>
                <select asp-for="DeveloperId" class="form-control" asp-items="ViewBag.DeveloperId"></select>
                <span asp-validation-for="DeveloperId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>Жанры</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var i in Model.Genres)
        {
            <tr>
                <td>
                    <li> @i.Name</li>
                </td>
                <td>
                    <a asp-action="DeleteGenre" asp-route-genreId ="@i.Id"
                                                asp-route-gameId="@Model.Id"
                       onclick = "return confirm('Вы уверены, что хотите удалить жанр данной игры?');">
                    Удалить
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

<form asp-action="AddGenre" asp-route-gameId="@Model.Id">
    <div class="form-group">
        <select asp-for="Genres" class="form-control" asp-items="ViewBag.Genres"></select>
        <input type="submit" value="Добавить жанр" class="btn btn-primary" />
    </div>
</form>

<div>
    <a asp-action="Index">Обратно к списку игр</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Games.WEB/Views/Games/Index.cshtml
@model IEnumerable<Games.BL.Game>

@{
    ViewData["Title"] = "Index";
}

<h1>Список игр</h1>

<p>
    <a asp-action="Create">Добавить игру</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Developer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genres)
            </th>
            <th></th>
        </tr>
    </thead>
<tbody>
@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Developer.Name)
        </td>
        <td>
            @foreach (var i in item.Genres)
            {
                <li> @i.Name</li>
            }
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Редактировать</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Посмотреть</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
            </td>
    </tr>
}
    </tbody>
</table>

Games.WEB/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Games.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Игры.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Игры.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Games" asp-action="Index">Игры</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Games.WEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>